apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default-ec2
spec:
  amiFamily: AL2
  role: KarpenterNodeRole-donggyu-eks  # IAM Role name
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: donggyu-eks
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: donggyu-eks

---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    metadata:
      labels:
        type: karpenter
    spec:
      nodeClassRef:
        name: default-ec2
      requirements:
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["t3"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.small", "t3.medium"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["small", "medium"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["ap-northeast-2a", "ap-northeast-2c", "ap-northeast-2b"]  # 사용 중인 AZ
      kubelet:
        maxPods: 110
  limits:
    cpu: "30"
    memory: "50Gi"
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 30s  # 30초
