apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: provisioner
spec:
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["t3.small", "t3.medium"]
    - key: topology.kubernetes.io/zone
      operator: In
      values: ["ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["ON_DEMAND"]
    - key: kubernetes.io/arch
      operator: In
      values: ["x86_64", "amd64"]
    - key: Service
      operator: In
      values: ["action"]

  limits:
    resources:
      cpu: "30"
      memory: "50Gi"

  provider:
    instanceProfile: eks-karpenter-action-instance-profile
    securityGroupSelector:
      Blueprint: donggyu-eks
    subnetSelector:
      environment: donggyu-eks
      managed-by: karpenter
    tags:
      Blueprint: donggyu-eks