apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: action
spec:
  replicas: 1  # 초기 Pod 수를 1로 설정
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
        type: karpenter
    spec:
      nodeSelector:
        type: karpenter
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values: ["karpenter"]
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - github-runner
            topologyKey: kubernetes.io/hostname
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        env:
        - name: RUNNER_LABELS
          value: "self-hosted,linux,x64"
        - name: RUNNER_NAME
          value: "runner"
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-runner-secret
              key: token
        - name: RUNNER_ORG
          value: "zkfmapf123"
        - name: REPO_URL
          value: "https://github.com/zkfmapf123/k8s-github-action"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "2Gi"