apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: action
  annotations:
    autoscaling.k8s.io/targetCPUUtilizationPercentage: "50"
    autoscaling.k8s.io/targetMemoryUtilizationPercentage: "50"
    autoscaling.k8s.io/minReplicas: "1"
    autoscaling.k8s.io/maxReplicas: "10"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      nodeSelector:
        Service: action
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        env:
        - name: RUNNER_NAME
          value: "runner"
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-runner-secret
              key: token
        - name: RUNNER_ORG
          value: "zkfmapf123"
        - name: REPO_URL
          value: "https://github.com/zkfmapf123/k8s-github-action"
        resources:
          requests:
            cpu: "500m"               ## 최소 사용량
            memory: "1Gi"
          limits:
            cpu: "1"                  ## 최대 사용량  
            memory: "1Gi" 