name: Bye World

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  bye:
    runs-on: self-hosted
    steps:
      - name: Hello World
        run: echo "Bye, World!"
