name: Bye World

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  hello:
    runs-on: [ self-hosted, linux, "x64", runner]
    steps:
      - name: Hello World
        run: echo "Bye, World!"
