name: Hello World 8

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - name: Hello World 8
        run: echo "Hello, World! 8" 